//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Rentals = new HashSet<Rental>();
        }

        public int CustomerID { get; set; }
        [RegularExpression(@"^(?:.*[a-z]){2,}$", ErrorMessage = "First name must contains only letters and have to be with at list 2 characters")]
        [Required(ErrorMessage = "First name is requierd")]
        public string FirstName { get; set; }

        [RegularExpression(@"^(?:.*[a-z]){2,}$", ErrorMessage = "Last name must contains only letters and have to be with at list 2 characters")]
        [Required(ErrorMessage = "Last name is requierd")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter phone number(10 digits)")]
        [StringLength(10)]
        [RegularExpression(@"^((\+91-?)|0)?[0-9]{10}$", ErrorMessage = "Entered Mobile No is not valid.")]
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
